/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_3 (
    input clk,
    input rst,
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] alu
  );
  
  
  
  always @* begin
    alu = 2'h0;
    
    case (alufn[4+1-:2])
      2'h0: begin
        alu = 8'h00;
        
        case (alufn[0+1-:2])
          2'h0: begin
            alu = a + b;
          end
          2'h1: begin
            alu = a - b;
          end
          2'h2: begin
            alu = a * b;
          end
        endcase
      end
      2'h1: begin
        
        case (alufn[0+3-:4])
          4'h8: begin
            alu = a & b;
          end
          4'he: begin
            alu = a | b;
          end
          4'h6: begin
            alu = a ^ b;
          end
          4'ha: begin
            alu = a;
          end
        endcase
      end
      2'h2: begin
        
        case (alufn[0+1-:2])
          2'h0: begin
            alu = a << b;
          end
          2'h1: begin
            alu = a >> b;
          end
          2'h3: begin
            alu = $signed(a) >>> b;
          end
        endcase
      end
      2'h3: begin
        
        case (alufn[1+1-:2])
          2'h1: begin
            alu = 8'h00;
            alu[0+0-:1] = a == b;
          end
          2'h2: begin
            alu = 8'h00;
            alu[0+0-:1] = $signed(a) < $signed(b);
          end
          2'h3: begin
            alu = 8'h00;
            alu[0+0-:1] = $signed(a) <= $signed(b);
          end
        endcase
      end
    endcase
  end
endmodule
