/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_alu_alu;
  wire [2-1:0] M_alu_extra;
  reg [6-1:0] M_alu_alufn;
  reg [8-1:0] M_alu_a;
  reg [8-1:0] M_alu_b;
  alu_2 alu (
    .clk(clk),
    .rst(rst),
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .alu(M_alu_alu),
    .extra(M_alu_extra)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_alu_alufn = io_dip[16+2+5-:6];
    M_alu_a = io_dip[8+7-:8];
    M_alu_b = io_dip[0+7-:8];
    led = {3'h0, io_button};
    io_led = io_dip;
    io_led[16+7-:8] = M_alu_alu;
    io_seg = 8'h00;
    if ({M_alu_extra[1+0-:1], M_alu_alu[7+0-:1]} == 2'h1 || {M_alu_extra[1+0-:1], M_alu_alu[7+0-:1]} == 2'h2) begin
      io_seg = 8'hff;
    end
  end
endmodule
